import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'converters.dart';
import 'tables.dart';

part 'app_database.g.dart'; // generated by build_runner

@DriftDatabase(tables: [
  Profile,
  FocusSessions,
  FocusTags,
  AppUsage,
  DoomscrollRules,
  RestrictionGroups,
  RestrictionGroupApps,
  AppLimits,
  AppRestrictions,
  InternetBlocks,
  BedtimeSchedule,
  WebsiteRules,
  BlockListCategories,
  UlimitSettings,
  PickupsLog,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  AppDatabase.connect(super.e);

  @override
  int get schemaVersion => 10;

  // Migrations are explicit (rather than "just delete and recreate")
  // because this is local user data — wiping someone's focus history on
  // an app update is not acceptable.
  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async => m.createAll(),
        onUpgrade: (m, from, to) async {
          // Every step is existence-guarded: devices can arrive from any
          // prior version AND from partial migrations aborted midway by
          // an earlier bug (a release once shipped schemaVersion=4
          // without its ALTER steps, leaving devices permanently stuck
          // with a duplicate-column error on every launch). PRAGMA
          // table_info is the ground truth, never the version pragma.
          if (from < 2) {
            await m.createAll();

            await _addColumnIfMissing(m, focusSessions, focusSessions.blockedPackages, 'blocked_packages');
            await _addColumnIfMissing(m, focusSessions, focusSessions.pauseNotifications, 'pause_notifications');
            await _addColumnIfMissing(m, focusSessions, focusSessions.blockInternet, 'block_internet');
            await _addColumnIfMissing(m, focusSessions, focusSessions.blockWebsites, 'block_websites');

            await _addColumnIfMissing(m, bedtimeSchedule, bedtimeSchedule.enabled, 'enabled');
            await _addColumnIfMissing(m, bedtimeSchedule, bedtimeSchedule.blockInternet, 'block_internet');
            await _addColumnIfMissing(m, bedtimeSchedule, bedtimeSchedule.selectedApps, 'selected_apps');

            // Carry all-day v1 blocks over as permanent restrictions.
            // Scheduled (HH:mm-window) blocks have no v2 equivalent —
            // the restriction engine composes windows from bedtime and
            // limits instead — so they intentionally do not migrate.
            if (await _tableExists('blocked_apps')) {
              await customStatement('''
              INSERT INTO app_restrictions (id, package_name, created_at, expires_at, permanent, invincible, enabled)
              SELECT COALESCE((SELECT MAX(id) FROM app_restrictions), 0) + ROWID,
                     package_name,
                     strftime('%s','now') * 1000,
                     NULL, 1, 0, 1
              FROM blocked_apps
              WHERE enabled = 1 AND schedule_start IS NULL AND schedule_end IS NULL
            ''');

              await m.deleteTable('blocked_apps');
            }
            if (await _tableExists('score_log')) {
              await m.deleteTable('score_log');
            }
            if (await _tableExists('emergency_unlocks')) {
              await m.deleteTable('emergency_unlocks');
            }
          }
          if (from < 3) {
            // v2 → v3: Tile Appearance setting.
            await _addColumnIfMissing(m, ulimitSettings, ulimitSettings.themeMode, 'theme_mode');
          }
          if (from < 4) {
            // v3 → v4: focus pause support + system indicator setting.
            await _addColumnIfMissing(m, focusSessions, focusSessions.pausedAt, 'paused_at');
            await _addColumnIfMissing(
                m, focusSessions, focusSessions.accumulatedPausedSeconds, 'accumulated_paused_seconds');
            await _addColumnIfMissing(m, ulimitSettings, ulimitSettings.focusIndicatorEnabled, 'focus_indicator_enabled');
          }
          if (from < 5) {
            // v4 → v5: permissions-onboarding-completed flag. Existing
            // installs are treated as already onboarded — they only own
            // a "re-enable after update" screen, not the full wizard.
            await _addColumnIfMissing(m, ulimitSettings, ulimitSettings.permissionsOnboardingCompleted, 'permissions_onboarding_completed');
            await customUpdate(
              'UPDATE ulimit_settings SET permissions_onboarding_completed = ?1',
              variables: [Variable.withBool(true)],
              updates: {ulimitSettings},
            );
          }
          if (from < 6) {
            // v5 → v6: user-created focus tags + the colored-tag toggle.
            // The FocusTags table is new, so createAll handles it; the
            // settings column is a plain additive ALTER.
            await _addColumnIfMissing(m, ulimitSettings, ulimitSettings.coloredSessionTags, 'colored_session_tags');
            await m.createTable(focusTags);
          }
          if (from < 7) {
            // v6 → v7: hide-nav-bar setting.
            await _addColumnIfMissing(m, ulimitSettings, ulimitSettings.hideNavBar, 'hide_nav_bar');
          }
          if (from < 8) {
            // v7 → v8: doomscroll blocking — per-app open counts on
            // AppUsage (new column) + the per-platform rule table.
            await _addColumnIfMissing(m, appUsage, appUsage.openCount, 'open_count');
            await m.createTable(doomscrollRules);
          }
          if (from < 9) {
            // v8 → v9: feed-only doomscroll flag on focus sessions
            // (Reels/Shorts surfaces ejected, app itself stays usable).
            await _addColumnIfMissing(
                m, focusSessions, focusSessions.blockDoomscroll, 'block_doomscroll');
          }
          if (from < 10) {
            // v9 → v10: separate OS-authoritative usage column. The
            // accessibility tracker's incremental adds and the
            // UsageStatsManager sync now write different columns, so a
            // sync overwrite can never be stacked on by the tracker
            // (and vice versa). See lib/data/usage_merge.dart.
            await _addColumnIfMissing(
                m, appUsage, appUsage.osForegroundSeconds, 'os_foreground_seconds');
          }
        },
        beforeOpen: (details) async {
          final m = createMigrator();

          // Self-healing for installs that skipped a migration step:
          // one release shipped schemaVersion=4 without the v4 ALTERs,
          // so devices on it report "up to date" while the columns are
          // missing. Verify the expected columns directly — idempotent,
          // runs on every open, costs a few PRAGMA reads.
          await _addColumnIfMissing(m, focusSessions, focusSessions.pausedAt, 'paused_at');
          await _addColumnIfMissing(
              m, focusSessions, focusSessions.accumulatedPausedSeconds, 'accumulated_paused_seconds');
          await _addColumnIfMissing(m, ulimitSettings, ulimitSettings.themeMode, 'theme_mode');
          await _addColumnIfMissing(
              m, ulimitSettings, ulimitSettings.focusIndicatorEnabled, 'focus_indicator_enabled');
          await _addColumnIfMissing(
              m, ulimitSettings,
              ulimitSettings.permissionsOnboardingCompleted,
              'permissions_onboarding_completed');
          await _addColumnIfMissing(
              m, ulimitSettings, ulimitSettings.coloredSessionTags, 'colored_session_tags');
          await _addColumnIfMissing(
              m, ulimitSettings, ulimitSettings.hideNavBar, 'hide_nav_bar');
          await _addColumnIfMissing(m, appUsage, appUsage.openCount, 'open_count');
          await _addColumnIfMissing(
              m, appUsage, appUsage.osForegroundSeconds, 'os_foreground_seconds');
          await _addColumnIfMissing(
              m, focusSessions, focusSessions.blockDoomscroll, 'block_doomscroll');
          if (await _tableExists('doomscroll_rules') == false) {
            await m.createTable(doomscrollRules);
          }

          // Ensure the singleton settings row exists so every reader
          // gets real values instead of "null until first write".
          final settings = await select(ulimitSettings).get();
          if (settings.isEmpty) {
            await into(ulimitSettings).insert(UlimitSettingsCompanion.insert());
          }
        },
      );

  /// True when the database currently has a table named [name].
  Future<bool> _tableExists(String name) async {
    final rows = await customSelect(
      "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?",
      variables: [Variable.withString(name)],
    ).get();
    return rows.isNotEmpty;
  }

  /// Adds [column] to [table] only when a column named [name] does not
  /// exist yet. PRAGMA table_info is the ground truth — never trust the
  /// schema_version pragma alone.
  Future<void> _addColumnIfMissing(
    Migrator m,
    TableInfo table,
    GeneratedColumn column,
    String name,
  ) async {
    final rows = await customSelect('PRAGMA table_info(${table.actualTableName})').get();
    final exists = rows.any((r) => r.data['name'] == name);
    if (!exists) {
      await m.addColumn(table, column);
    }
  }

  Future<void> wipeAllData() async {
    await transaction(() async {
      // Raw statements rather than delete(table): the table list here
      // spans several generated TableInfo types, and the SQL names are
      // stable parts of the schema contract.
      for (final name in [
        'app_usage',
        'pickups_log',
        'focus_sessions',
        'app_restrictions',
        'app_limits',
        'internet_blocks',
        'restriction_groups',
        'restriction_group_apps',
        'website_rules',
        'block_list_categories',
        'bedtime_schedule',
        'doomscroll_rules',
      ]) {
        await customStatement('DELETE FROM $name');
      }
      await customStatement('DELETE FROM sqlite_sequence');
    });
  }
}

LazyDatabase _openConnection() {
  // LazyDatabase defers opening the file until first query, off the
  // app's cold-start critical path — avoids a startup jank spike on
  // low-end devices where disk I/O + SQLite init can take 30-80ms.
  return LazyDatabase(() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(p.join(dir.path, 'ulimit.sqlite'));
    return NativeDatabase.createInBackground(file, logStatements: false);
  });
}
