import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'tables.dart';

part 'app_database.g.dart'; // generated by build_runner

@DriftDatabase(tables: [
  Profile,
  FocusSessions,
  AppUsage,
  RestrictionGroups,
  RestrictionGroupApps,
  BlockedApps,
  BedtimeSchedule,
  ScoreLog,
  EmergencyUnlocks,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  // Migrations start here once schemaVersion > 1. Left explicit (rather
  // than "just delete and recreate") because this is local user data —
  // wiping someone's focus history on an app update is not acceptable.
  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async => m.createAll(),
      );
}

LazyDatabase _openConnection() {
  // LazyDatabase defers opening the file until first query, off the
  // app's cold-start critical path — avoids a startup jank spike on
  // low-end devices where disk I/O + SQLite init can take 30-80ms.
  return LazyDatabase(() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(p.join(dir.path, 'ulimit.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
