import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'converters.dart';
import 'tables.dart';

part 'app_database.g.dart'; // generated by build_runner

@DriftDatabase(tables: [
  Profile,
  FocusSessions,
  AppUsage,
  RestrictionGroups,
  RestrictionGroupApps,
  AppLimits,
  AppRestrictions,
  InternetBlocks,
  BedtimeSchedule,
  WebsiteRules,
  BlockListCategories,
  UlimitSettings,
  PickupsLog,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  AppDatabase.connect(super.e);

  @override
  int get schemaVersion => 4;

  // Migrations are explicit (rather than "just delete and recreate")
  // because this is local user data — wiping someone's focus history on
  // an app update is not acceptable.
  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async => m.createAll(),
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            // v1 → v2:
            //  - new tables: app_limits, app_restrictions, internet_blocks,
            //    website_rules, block_list_categories, ulimit_settings
            //  - focus_sessions gains the per-session policy columns
            //  - bedtime_schedule gains enabled + block_internet + selected_apps
            //  - gamification remnants dropped (score_log, emergency_unlocks)
            //  - blocked_apps (schedule-string blocks) → app_restrictions
            await m.createAll();

            await m.addColumn(focusSessions, focusSessions.blockedPackages);
            await m.addColumn(focusSessions, focusSessions.pauseNotifications);
            await m.addColumn(focusSessions, focusSessions.blockInternet);
            await m.addColumn(focusSessions, focusSessions.blockWebsites);

            await m.addColumn(bedtimeSchedule, bedtimeSchedule.enabled);
            await m.addColumn(bedtimeSchedule, bedtimeSchedule.blockInternet);
            await m.addColumn(bedtimeSchedule, bedtimeSchedule.selectedApps);

            // Carry all-day v1 blocks over as permanent restrictions.
            // Scheduled (HH:mm-window) blocks have no v2 equivalent —
            // the restriction engine composes windows from bedtime and
            // limits instead — so they intentionally do not migrate.
            await customStatement('''
              INSERT INTO app_restrictions (id, package_name, created_at, expires_at, permanent, invincible, enabled)
              SELECT COALESCE((SELECT MAX(id) FROM app_restrictions), 0) + ROWID,
                     package_name,
                     strftime('%s','now') * 1000,
                     NULL, 1, 0, 1
              FROM blocked_apps
              WHERE enabled = 1 AND schedule_start IS NULL AND schedule_end IS NULL
            ''');

            await m.deleteTable('blocked_apps');
            await m.deleteTable('score_log');
            await m.deleteTable('emergency_unlocks');
          }
          if (from < 3) {
            // v2 → v3: Tile Appearance setting.
            await m.addColumn(ulimitSettings, ulimitSettings.themeMode);
          }
        },
        beforeOpen: (details) async {
          // Ensure the singleton settings row exists so every reader
          // gets real values instead of "null until first write".
          final settings = await select(ulimitSettings).get();
          if (settings.isEmpty) {
            await into(ulimitSettings).insert(UlimitSettingsCompanion.insert());
          }
        },
      );

  Future<void> wipeAllData() async {
    await transaction(() async {
      // Raw statements rather than delete(table): the table list here
      // spans several generated TableInfo types, and the SQL names are
      // stable parts of the schema contract.
      for (final name in [
        'app_usage',
        'pickups_log',
        'focus_sessions',
        'app_restrictions',
        'app_limits',
        'internet_blocks',
        'restriction_groups',
        'restriction_group_apps',
        'website_rules',
        'block_list_categories',
        'bedtime_schedule',
      ]) {
        await customStatement('DELETE FROM $name');
      }
      await customStatement('DELETE FROM sqlite_sequence');
    });
  }
}

LazyDatabase _openConnection() {
  // LazyDatabase defers opening the file until first query, off the
  // app's cold-start critical path — avoids a startup jank spike on
  // low-end devices where disk I/O + SQLite init can take 30-80ms.
  return LazyDatabase(() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(p.join(dir.path, 'ulimit.sqlite'));
    return NativeDatabase.createInBackground(file, logStatements: false);
  });
}
